### ISSUE TITLE
Simplified Installation

### ISSUE THREAD

**Issue by beornlake** [CallMeKass/pfSense-palenight#1]
Here's an alternate command to drop into the **Diagnostics > Command Prompt** page that bypasses the `install.php` process entirely:
```
curl -O --output-dir /usr/local/www/css https://raw.githubusercontent.com/callmekass/pfSense-palenight/main/callmekass-palenight.css
```

**Comment by tyler-holm** [comment]
This is great but I'm planning to add some features to the install script down the line. Sticking with the script for now.
