### ISSUE TITLE
BandwidthD looks terrible when in use with this theme

### ISSUE THREAD

**Issue by jh20001** [CallMeKass/pfSense-palenight#12]
I was unsure if I should say anything or not since this could lead to a rabbit hole as BandwidthD is an optional installable package. But i installed it and it looks terrible (most likely since the css doesn't cover it, I'm sure). 

Anyway, pointing it out just in case! :)

**Comment by tyler-holm** [comment]
I looked into BandwidthD and unfortunately it uses styling that isn't included in the standard pfsense styling file so it will not be supported. This is an issue with a lot of installable packages that implement their own styling. Closing this issue and marking as "not planned"
