### ISSUE TITLE
Navigation Tabs Border Color

### ISSUE THREAD

**Issue by beornlake** [CallMeKass/pfSense-palenight#7]
Not sure if this is a 'bug' or 'working as intended', but the `border-bottom` attribute of inactive navigation tabs might need to be changed from `--foreground` to `--contrast` at [line 251](https://github.com/callmekass/pfSense-palenight/blob/main/callmekass-palenight.css#L251).

In the official themes, inactive tabs don't have a visible bottom border, which improves contrast when determining which tab is 'active' at a glance. With the current settings, it feels like there may not be enough contrast here:

![Screenshot 2023-04-07-151334](https://user-images.githubusercontent.com/3237644/230673104-56604cd3-0c47-4080-b716-c63625935e0d.jpg)

**Comment by tyler-holm** [comment]
Changing the background color on active tabs to --second-background. This should make the active tab more apparent.

**Comment by tyler-holm** [comment]
Fix is done. Waiting for merge to main.
